// Code generated by MockGen. DO NOT EDIT.
// Source: internal/upload/upload.go
//
// Generated by this command:
//
//	mockgen -source=internal/upload/upload.go -destination=internal/upload/mock_upload_test.go -package=upload
//

// Package upload is a generated GoMock package.
package upload

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, id, filename, contentType, status, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, id, filename, contentType, status, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, id, filename, contentType, status, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, id, filename, contentType, status, userID)
}

// MockPresigner is a mock of Presigner interface.
type MockPresigner struct {
	ctrl     *gomock.Controller
	recorder *MockPresignerMockRecorder
	isgomock struct{}
}

// MockPresignerMockRecorder is the mock recorder for MockPresigner.
type MockPresignerMockRecorder struct {
	mock *MockPresigner
}

// NewMockPresigner creates a new mock instance.
func NewMockPresigner(ctrl *gomock.Controller) *MockPresigner {
	mock := &MockPresigner{ctrl: ctrl}
	mock.recorder = &MockPresignerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPresigner) EXPECT() *MockPresignerMockRecorder {
	return m.recorder
}

// Presign mocks base method.
func (m *MockPresigner) Presign(ctx context.Context, key, method string, ttl time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Presign", ctx, key, method, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Presign indicates an expected call of Presign.
func (mr *MockPresignerMockRecorder) Presign(ctx, key, method, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Presign", reflect.TypeOf((*MockPresigner)(nil).Presign), ctx, key, method, ttl)
}

// MockPipeline is a mock of Pipeline interface.
type MockPipeline struct {
	ctrl     *gomock.Controller
	recorder *MockPipelineMockRecorder
	isgomock struct{}
}

// MockPipelineMockRecorder is the mock recorder for MockPipeline.
type MockPipelineMockRecorder struct {
	mock *MockPipeline
}

// NewMockPipeline creates a new mock instance.
func NewMockPipeline(ctrl *gomock.Controller) *MockPipeline {
	mock := &MockPipeline{ctrl: ctrl}
	mock.recorder = &MockPipelineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPipeline) EXPECT() *MockPipelineMockRecorder {
	return m.recorder
}

// Signal mocks base method.
func (m *MockPipeline) Signal(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signal", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Signal indicates an expected call of Signal.
func (mr *MockPipelineMockRecorder) Signal(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockPipeline)(nil).Signal), ctx, id)
}

// Start mocks base method.
func (m *MockPipeline) Start(ctx context.Context, id, contentType, filename string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, id, contentType, filename)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockPipelineMockRecorder) Start(ctx, id, contentType, filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockPipeline)(nil).Start), ctx, id, contentType, filename)
}
