// Code generated by MockGen. DO NOT EDIT.
// Source: internal/upload/upload.go
//
// Generated by this command:
//
//	mockgen -source=internal/upload/upload.go -destination=internal/upload/mock_upload_test.go -package=upload
//

// Package upload is a generated GoMock package.
package upload

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockStore) Save(id, name, ext string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", id, name, ext, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockStoreMockRecorder) Save(id, name, ext, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockStore)(nil).Save), id, name, ext, data)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, id, filename, ext, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, id, filename, ext, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, id, filename, ext, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, id, filename, ext, status)
}

// MockUploadStarter is a mock of UploadStarter interface.
type MockUploadStarter struct {
	ctrl     *gomock.Controller
	recorder *MockUploadStarterMockRecorder
	isgomock struct{}
}

// MockUploadStarterMockRecorder is the mock recorder for MockUploadStarter.
type MockUploadStarterMockRecorder struct {
	mock *MockUploadStarter
}

// NewMockUploadStarter creates a new mock instance.
func NewMockUploadStarter(ctrl *gomock.Controller) *MockUploadStarter {
	mock := &MockUploadStarter{ctrl: ctrl}
	mock.recorder = &MockUploadStarterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploadStarter) EXPECT() *MockUploadStarterMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockUploadStarter) Start(ctx context.Context, id, ext, filename string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, id, ext, filename)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockUploadStarterMockRecorder) Start(ctx, id, ext, filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockUploadStarter)(nil).Start), ctx, id, ext, filename)
}
